name: Primeiro Workflow

on:

  push:
    branches:
      - develop
      - main
      - master
  pull_request:
    branches: [main, master]

jobs:
  Primeiro-Fluxo:

    name: Job 1 
    runs-on: ubuntu-latest
    steps:  
      - name: Passo 1
        run: echo "Executando o primeiro passo"
      - name: Passo 2
        run: echo "Executando o segundo passo"
      - name: Passo 3
        run: echo "Executando o terceiro passo"

  Segundo-Fluxo:

    name: Job 2 
    runs-on: ubuntu-latest
    steps:  
      - name: Passo 1
        run: echo "Executando o quarto passo"
      - name: Passo 2
        run: echo "Executando o quinto passo"
      - name: Passo 3
        run: echo "Executando o sexto passo"
        
  Terceiro-Fluxo:

    name: Job 3 
    runs-on: ubuntu-latest
    steps:  
      - name: Passo 1
        run: echo "Executando o quarto passo"
      - name: Passo 2
        run: echo "Executando o quinto passo"
      - name: Passo 3
        run: echo "Executando o sexto passo"

    
